src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

build/deploy/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/Hosp_WrapperDoctorsCsvImport.cls
public with sharing class Hosp_WrapperDoctorsCsvImport {
    public String doctorIdWrapper { get; set; }
    public String doctorNameWrapper { get; set; }
    public String doctorFirstNameWrapper { get; set; }
    public String doctorCountryWrapper { get; set; }
    public String doctorCityWrapper { get; set; }
    public Boolean doctorIsSelectedWrapper { get; set; }
    public Boolean doctorIsSelectedBeforeImport { get; set; }
    public Integer doctorInformationAfterImport { get; set; }

    public Hosp_WrapperDoctorsCsvImport(Doctor__c doc) {
        doctorIdWrapper = doc.Id;
        doctorNameWrapper = doc.Name;
        doctorFirstNameWrapper = doc.FirstName__c;
        doctorCountryWrapper = doc.Country__c;
        doctorCityWrapper = doc.City__c;
        doctorIsSelectedWrapper = true;
        doctorInformationAfterImport = 0;
        doctorIsSelectedBeforeImport = false;
    }

    public void setDoctorIsSelectedBeforeImport() {
        this.doctorIsSelectedBeforeImport = true;
    }
}