src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

build/deploy/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/Hosp_DoctorsPublicSiteControllerExt.cls
public with sharing class Hosp_DoctorsPublicSiteControllerExt {
    public List<Doctor__c> randomDoctors { get; set; }
    Integer numberOfRandomDoctors;

    
    public Hosp_DoctorsPublicSiteControllerExt(ApexPages.StandardController controller) {
        numberOfRandomDoctors = 10;

        randomDoctors = generateRandomDoctors();
    }

    private List<Doctor__c> generateRandomDoctors() {
        Integer count = [SELECT COUNT() FROM Doctor__c];
        Integer rand = Math.floor(Math.random() * count).intValue();
        List<Doctor__c> doctors = [SELECT FirstLastName__c,
                Email__c,
                City__c,
                Country__c
            FROM Doctor__c
            LIMIT :numberOfRandomDoctors
            OFFSET :rand];

        return doctors;
    }
}