src/objects/Hospital__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <label>PostalCode</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Hospital</label>
    <nameField>
        <label>Hospital Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hospitals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

build/deploy/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>USA</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/Hosp_HospitalsSoap.cls
global class Hosp_HospitalsSoap {
    webService static Hosp_HospitalWrapperForRest upsertHospital(String hospitalId, String name, String country, String city,
            String postalCode, String street) {
        Hospital__c hospital = new Hospital__c();
        if (String.isNotBlank(hospitalId)) {
            hospital = new Hospital__c(Id = hospitalId);
        }
        if (String.isNotBlank(name)) {
            hospital.Name = name;
        }
        if (String.isNotBlank(country)) {
            hospital.Country__c = country;
        }
        if (String.isNotBlank(city)) {
            hospital.City__c = city;
        }
        if (String.isNotBlank(postalCode)) {
            hospital.PostalCode__c = postalCode;
        }
        if (String.isNotBlank(street)) {
            hospital.Street__c = street;
        }
        if (String.isNotBlank(street)) {
            hospital.Street__c = street;
        }
        upsert hospital;
        return new Hosp_HospitalWrapperForRest(hospital);
    }

    webService static List<Hosp_HospitalWrapperForRest> getHospitals(String hospitalId, String name, String country, String city,
            String postalCode, String street) {
        String query = 'SELECT Id, Name, Country__c, City__c, PostalCode__c, Street__c, ExternalId__c FROM Hospital__c';
        List<Hospital__c> hospitals = Database.query(query);
        List<Hosp_HospitalWrapperForRest> hospitalsWrapperForSOAP = new List<Hosp_HospitalWrapperForRest>();

        for (Hospital__c hospital : hospitals) {
            hospitalsWrapperForSOAP.add(new Hosp_HospitalWrapperForRest(hospital));
        }
        return hospitalsWrapperForSOAP;
    }
}